#!/usr/bin/env python3
"""Turn an OpenAPI/Swagger spec into a working single-file Python CLI.

Lists operations, or generates a stdlib-only CLI (argparse + urllib) where each
operation becomes a subcommand. The generated CLI is self-contained: copy it
anywhere Python 3.9+ exists.

Usage:
  spec_to_cli.py --spec openapi.json --list
  spec_to_cli.py --spec https://host/openapi.json --out api_cli.py
  python api_cli.py --base-url https://host list-pets --limit 3

Auth: the generated CLI reads its token from the env var named by --token-env
(default API_TOKEN) and sends it as a bearer token. Override with --token-env.
"""
from __future__ import annotations

import argparse
import json
import keyword
import re
import sys
import urllib.parse
import urllib.request

TEMPLATE = '''#!/usr/bin/env python3
"""Auto-generated CLI for {title} (spec {version}).

Generated by api-spec-hunt/spec_to_cli.py. Auth: read from ${token_env} if set.
Override target with --base-url. Bodies are passed as --data '<json>'.
"""
import argparse, json, os, sys, urllib.error, urllib.parse, urllib.request

BASE_URL = {base_url!r}
OPERATIONS = {operations!r}


def _emit(text):
    try:
        print(text)
    except BrokenPipeError:  # piping into head/less
        try:
            sys.stdout.close()
        finally:
            os._exit(0)


def call(base_url, method, path, path_params, query, body, token_env, extra_headers):
    url = base_url.rstrip("/") + path
    for name, value in path_params.items():
        url = url.replace("{{" + name + "}}", urllib.parse.quote(str(value), safe=""))
    clean = {{k: v for k, v in query.items() if v is not None}}
    if clean:
        url += ("&" if "?" in url else "?") + urllib.parse.urlencode(clean, doseq=True)
    data = None
    if body is not None:
        data = body.encode()
    headers = {{"Accept": "application/json"}}
    if data:
        headers["Content-Type"] = "application/json"
    token = os.environ.get(token_env)
    if token:
        headers["Authorization"] = "Bearer " + token
    headers.update(extra_headers or {{}})
    req = urllib.request.Request(url, data=data, method=method.upper(), headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=60) as r:
            raw, status, hdrs = r.read(), r.status, dict(r.headers)
    except urllib.error.HTTPError as e:
        raw, status, hdrs = e.read(), e.code, dict(e.headers or {{}})
    except Exception as e:
        print(json.dumps({{"error": str(e), "url": url}})); return 1
    ctype = (hdrs.get("Content-Type") or "").lower()
    if "json" in ctype:
        try:
            _emit(json.dumps(json.loads(raw.decode()), indent=2)); return 0 if status < 400 else 1
        except ValueError:
            pass
    _emit("HTTP %s\\n%s" % (status, raw.decode("utf-8", "replace")))
    return 0 if status < 400 else 1


def main():
    ap = argparse.ArgumentParser(description={title!r} + " CLI")
    ap.add_argument("--base-url", default=BASE_URL)
    ap.add_argument("--token-env", default={token_env!r})
    ap.add_argument("-H", "--header", action="append", default=[],
                    help="extra header Key:Value (repeatable)")
    sub = ap.add_subparsers(dest="command", required=True)
    for name, spec in OPERATIONS.items():
        p = sub.add_parser(name, help=spec["method"] + " " + spec["path"])
        for pp in spec["path_params"]:
            p.add_argument("--" + pp.replace("_", "-"), dest=pp, required=True)
        for qp in spec["query"]:
            p.add_argument("--" + qp.replace("_", "-"), dest=qp)
        if spec["body"]:
            p.add_argument("--data", help="JSON request body")
        p.add_argument("--dry-run", action="store_true")
    ns = ap.parse_args()
    spec = OPERATIONS[ns.command]
    kv = ns.__dict__
    path_params = {{k: kv[k] for k in spec["path_params"]}}
    query = {{k: kv.get(k) for k in spec["query"]}}
    body = kv.get("data")
    if body:
        try:
            json.loads(body)
        except ValueError as e:
            ap.error("--data is not valid JSON: %s" % e)
    if ns.dry_run:
        print(json.dumps({{"method": spec["method"], "path": spec["path"],
                           "path_params": path_params, "query": query,
                           "body": json.loads(body) if body else None}}, indent=2))
        return 0
    headers = {{}}
    for item in ns.header:
        k, _, v = item.partition(":")
        headers[k.strip()] = v.strip()
    return call(ns.base_url, spec["method"], spec["path"], path_params, query, body,
                ns.token_env, headers)


if __name__ == "__main__":
    sys.exit(main())
'''


def slug(text: str) -> str:
    # insert separators at case/number boundaries so addPet -> add-pet
    text = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "-", text)
    text = re.sub(r"(?<=[A-Z])(?=[A-Z][a-z])", "-", text)
    text = re.sub(r"[^0-9A-Za-z]+", "-", text).strip("-").lower()
    if not text or keyword.iskeyword(text):
        text = "op-" + text
    return text or "op"


def load_spec(src: str) -> dict:
    if src.startswith(("http://", "https://")):
        with urllib.request.urlopen(src, timeout=30) as r:
            raw = r.read().decode("utf-8", "replace")
    else:
        with open(src, encoding="utf-8") as fh:
            raw = fh.read()
    try:
        return json.loads(raw)
    except ValueError:
        try:
            import yaml  # type: ignore
        except ImportError:
            sys.exit("spec is not JSON and PyYAML is not installed (pip install pyyaml)")
        return yaml.safe_load(raw)


def base_url_of(spec: dict) -> str:
    servers = spec.get("servers") or []
    if servers and isinstance(servers, list):
        return (servers[0].get("url") or "").rstrip("/")
    host, base = spec.get("host"), spec.get("basePath", "")
    scheme = (spec.get("schemes") or ["https"])[0]
    if host:
        return f"{scheme}://{host}{base}".rstrip("/")
    return ""


def operations_of(spec: dict) -> dict:
    ops: dict[str, dict] = {}
    methods = ("get", "post", "put", "patch", "delete", "head", "options")
    for path, item in (spec.get("paths") or {}).items():
        if not isinstance(item, dict):
            continue
        for method, op in item.items():
            if method.lower() not in methods or not isinstance(op, dict):
                continue
            names = [slug(op.get("operationId") or f"{method}-{path}")]
            # also register a path-derived alias when operationId differs
            alias = slug(f"{method}-{path}")
            for candidate in (names[0], alias):
                if candidate not in ops:
                    ops[candidate] = {
                        "method": method.upper(),
                        "path": path,
                        "summary": (op.get("summary") or "").strip(),
                        "path_params": [p["name"] for p in (op.get("parameters") or [])
                                        if isinstance(p, dict) and p.get("in") == "path"],
                        "query": [p["name"] for p in (op.get("parameters") or [])
                                  if isinstance(p, dict) and p.get("in") == "query"],
                        "body": bool(op.get("requestBody")),
                    }
    return ops


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate a CLI from an OpenAPI/Swagger spec.")
    ap.add_argument("--spec", required=True, help="spec file path or URL")
    ap.add_argument("--out", help="write generated CLI here")
    ap.add_argument("--list", action="store_true", help="list operations and exit")
    ap.add_argument("--base-url", help="override base URL in the generated CLI")
    ap.add_argument("--token-env", default="API_TOKEN", help="env var holding the bearer token")
    args = ap.parse_args()

    spec = load_spec(args.spec)
    info = spec.get("info") or {}
    title = info.get("title") or "API"
    version = info.get("version") or "?"
    base = args.base_url or base_url_of(spec)
    if base.startswith("/") and args.spec.startswith(("http://", "https://")):
        # server URLs are often relative (e.g. "/api/v3"); anchor to the spec's origin
        parsed = urllib.parse.urlsplit(args.spec)
        base = f"{parsed.scheme}://{parsed.netloc}{base}"
    ops = operations_of(spec)

    if args.list:
        print(f"{title} {version} — base {base or '(none declared)'} — {len(ops)} operations")
        for name, spec_op in sorted(ops.items()):
            print(f"  {name:<34} {spec_op['method']:<6} {spec_op['path']}")
        return 0

    if not base:
        sys.exit("no base URL in spec; pass --base-url")

    rendered = TEMPLATE.format(title=title, version=version, base_url=base,
                               operations=ops, token_env=args.token_env)
    compile(rendered, "<generated>", "exec")  # fail early on template bugs

    if args.out:
        with open(args.out, "w", encoding="utf-8") as fh:
            fh.write(rendered)
        import os
        os.chmod(args.out, 0o755)
        print(f"wrote {args.out} ({len(ops)} operations, base {base})")
    else:
        print(rendered)
    return 0


if __name__ == "__main__":
    sys.exit(main())